name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - run: sudo apt-get install alsa-base alsa-utils

      - run: pip install pytest pygame

      - run: pytest -v
        env:
          SDL_VIDEODRIVER: dummy
          SDL_AUDIODRIVER: dummy
          PYTHONPATH: .

